---

- name: Gather facts, for debugging
  setup:
    gather_subset:
      - 'network'
  tags: [ never, facts ]

- name: Show configuration
  vars:
    msg: |
      freeipa_client_server:         '{{ freeipa_client_server }}'
      freeipa_client_hostname:       '{{ freeipa_client_hostname }}'
      freeipa_client_fqdn:           '{{ freeipa_client_fqdn }}'
      freeipa_client_domain:         '{{ freeipa_client_domain }}'
      freeipa_client_realm:          '{{ freeipa_client_realm }}'
      freeipa_client_principal:      '{{ freeipa_client_principal | default('UNDEFINED') }}'
      freeipa_client_password:       '{{ freeipa_client_password | default('UNDEFINED') }}'
      -----
      freeipa_client_install_options: {{ freeipa_client_install_options }}
  debug:
    msg: "{{ msg.split('\n') }}"
  tags: [ never, debug ]

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: [ never, debug_all ]
